### ISSUE TITLE
All items from mod do not drop

### ISSUE THREAD

**Issue by ghost** [Siuolplex/wood-you-dye#1]
Hi!
Not sure if this is intentional or not, but any and all items/blocks in this mod do not drop when broken, they simply vanish. You can craft and place them, but you cannot pick them back up when breaking them.

Is this intentional, or a bug?

So far, no error logs are showing up or spamming in the console (using MultiMC launcher) It's just a weird bug (maybe?)

Tried rejoining/reloading my world. Nothing
Tried relaunching my game. Nothing

https://github.com/Siuolplex/wood-you-dye/assets/61992533/cbc5f5a7-c6fd-47b0-842f-87b3b18c4f02

Here is a REALLY quick video of such. Breaking one of the blocks, only for it to not drop anything/itself. I have another sample of doing this with a door, sign and a wooden block- but the video is too large.

**Comment by Siuolplex** [comment]
Hi! I just saw this, and this is definitely not intended behavior lol. Ill look into it.

**Comment by Siuolplex** [comment]
Just looked into it, how did I miss that

**Comment by Siuolplex** [comment]
Alright fixed locally will push commit very soon
